spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_info
    username: root
    password: Tiger@13
  jpa:
    hibernate:
      ddl-auto: update

openweathermap:
  api:
    key: give-our-own-Key

google:
  geocoding:
    api:
      key: give-our-own-Key

server:
  port: 8082
